//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenDing.Repository.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIS_Interface", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HIS_Interface(string TradeCode, string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIS_Interface", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HIS_InterfaceAsync(string TradeCode, string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIPMessageServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HIPMessageServer(string action, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HIPMessageServer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HIPMessageServerAsync(string action, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_HIS_05", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TCM_HIS_05(string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_HIS_05", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TCM_HIS_05Async(string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_HIS_06", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TCM_HIS_06(string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_HIS_06", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TCM_HIS_06Async(string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_AE_04", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TCM_AE_04(string InputParameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCM_AE_04", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TCM_AE_04Async(string InputParameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : BenDing.Repository.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<BenDing.Repository.ServiceReference.WebServiceSoap>, BenDing.Repository.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HIS_Interface(string TradeCode, string InputParameter) {
            return base.Channel.HIS_Interface(TradeCode, InputParameter);
        }
        
        public System.Threading.Tasks.Task<string> HIS_InterfaceAsync(string TradeCode, string InputParameter) {
            return base.Channel.HIS_InterfaceAsync(TradeCode, InputParameter);
        }
        
        public string HIPMessageServer(string action, string message) {
            return base.Channel.HIPMessageServer(action, message);
        }
        
        public System.Threading.Tasks.Task<string> HIPMessageServerAsync(string action, string message) {
            return base.Channel.HIPMessageServerAsync(action, message);
        }
        
        public string TCM_HIS_05(string InputParameter) {
            return base.Channel.TCM_HIS_05(InputParameter);
        }
        
        public System.Threading.Tasks.Task<string> TCM_HIS_05Async(string InputParameter) {
            return base.Channel.TCM_HIS_05Async(InputParameter);
        }
        
        public string TCM_HIS_06(string InputParameter) {
            return base.Channel.TCM_HIS_06(InputParameter);
        }
        
        public System.Threading.Tasks.Task<string> TCM_HIS_06Async(string InputParameter) {
            return base.Channel.TCM_HIS_06Async(InputParameter);
        }
        
        public string TCM_AE_04(string InputParameter) {
            return base.Channel.TCM_AE_04(InputParameter);
        }
        
        public System.Threading.Tasks.Task<string> TCM_AE_04Async(string InputParameter) {
            return base.Channel.TCM_AE_04Async(InputParameter);
        }
    }
}
